name: LimbusEGOWeapons
version: 2.5.2
main: me.yisang.limbus.LimbusEGOWeapons
description: Face the sin, Save the E.G.O.
api-version: "1.21.4"
softdepend: [ProtocolLib]
commands:
  getego:
    description: 取得 E.G.O 裝備
    permission: limbus.admin